### ISSUE TITLE
DOKAN_EXPLICIT_LINK If I use this I always get an acces violation in the DokanDLL on Win32

### ISSUE THREAD

**Issue by EdwinDijkshoorn** [dokan-dev/dokan-delphi#13]
Reproduction:

program Mirror;
.......
  dokanOperations.Unmounted := MirrorUnmounted;
  dokanOperations.FindStreams := MirrorFindStreams;
  dokanOperations.Mounted := MirrorMounted;

  if DokanLoad('C:\Program Files\Dokan\DokanLibrary-2.0.6\x86\dokan2.dll') then
  begin
    Writeln(ErrOutput, 'loaded'); //<---- This is printed
  end;
    DokanInit;

  Writeln(ErrOutput, DokanVersion.ToString);
  status := DokanMain(dokanOptions, dokanOperations);   <--- Throws Exception

---------------------------
Debugger Exception Notification
---------------------------
Project Mirror.exe raised exception class $C0000005 with message 'access violation at 0x7b015f37: read of address 0x000000d2'.
---------------------------
Break   Continue   Copy   Help   
---------------------------

**Comment by landrix** [comment]
do you have installed Dokan Library 2.0.6?
https://github.com/dokan-dev/dokany/releases/tag/v2.0.6.1000
or newer?

**Comment by EdwinDijkshoorn** [comment]
2.0.6.10000 Tried the mirror example with the changes posted above compiled for win32. 64bit (C:\Program Files\Dokan\DokanLibrary-2.0.6\x86\dokan2.dll) does work.

**Comment by landrix** [comment]
and now?

**Comment by EdwinDijkshoorn** [comment]
Yes, No Accesviolation ! 
Tanks for the quick fix
